# config/config.yaml

# Path to your samples table (tsv with columns fq1, fq2 per sample)
samples: "samples.tsv"

# Reference FASTA for bowtie2 index
reference: "data/reference/reference.fa"

# Thread counts for various steps
threads:
  build_index: 4
  map_reads:   4
  samtools:    4
  qc:          2

# Trimmomatic settings (adapter + per‐step options)
trim:
  adapter: "resources/adapters/TruSeq3-PE.fa"
  options:
    - "ILLUMINACLIP:{adapter}:2:30:10"
    - "LEADING:3"
    - "TRAILING:3"
    - "SLIDINGWINDOW:4:15"
    - "MINLEN:36"

# Bowtie2 insert size settings
bowtie:
  minins: 200
  maxins: 1000

# Skip flags (all default to False)
skip_trimming: False
skip_fastqc:   False
skip_qualimap: False
